import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions — Nebulaa.ai',
  description: 'Terms & Conditions of Service for Nebulaa (Noburo Business Services LLP). Please read before using the Nebulaa platform.',
}

function Section({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="font-heading font-bold text-xl text-ink mb-4 flex items-center gap-3">
        <span className="flex-shrink-0 w-8 h-8 rounded-full bg-gold/15 text-gold-text text-sm font-bold flex items-center justify-center">
          {number}
        </span>
        {title}
      </h2>
      <div className="space-y-3 text-ink-2 font-body text-sm leading-relaxed pl-11">
        {children}
      </div>
    </section>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p>{children}</p>
}

function Ul({ items }: { items: string[] }) {
  return (
    <ul className="space-y-1.5">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2">
          <span className="text-gold-text mt-1 flex-shrink-0">•</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return <h3 className="font-body font-bold text-ink-2 mt-5 mb-2">{children}</h3>
}

function Numbered({ items }: { items: string[] }) {
  return (
    <ol className="space-y-2 list-none">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-3">
          <span className="flex-shrink-0 w-5 h-5 rounded-full bg-white/5 border border-rule text-[10px] font-bold text-muted flex items-center justify-center mt-0.5">
            {i + 1}
          </span>
          <span>{item}</span>
        </li>
      ))}
    </ol>
  )
}

export default function TermsPage() {
  return (
    <main className="bg-ground min-h-screen pt-28 pb-24">
      <div className="max-w-3xl mx-auto px-4 md:px-8">
        {/* Header */}
        <div className="mb-12">
          <div className="h-1 w-16 bg-gradient-to-r from-gold to-gold/30 rounded-full mb-6" />
          <p className="font-body text-xs font-bold tracking-widest uppercase text-gold-text mb-3">Legal</p>
          <h1 className="font-heading font-bold text-4xl md:text-5xl text-ink tracking-tight mb-4">
            Terms & Conditions
          </h1>
          <div className="flex flex-wrap gap-4 font-body text-xs text-muted">
            <span>Effective Date: 10 March 2025</span>
            <span>·</span>
            <span>Version 1.0</span>
            <span>·</span>
            <span>Governing Entity: Noburo Business Services LLP, India</span>
          </div>
        </div>

        {/* Intro */}
        <div className="mb-10 p-5 bg-gold/5 border border-gold/20 rounded-2xl font-body text-sm text-ink-2 leading-relaxed">
          Please read these Terms & Conditions carefully before accessing or using the Nebulaa platform. By registering, accessing, or using Nebulaa in any capacity — including during a free trial — you confirm that you have read, understood, and agree to be bound by these Terms. If you do not agree, do not use the platform.
        </div>

        <div className="divide-y divide-rule">

          <Section number={1} title="Definitions">
            <P>For the purposes of these Terms, the following definitions apply:</P>
            <Ul items={[
              '"Company", "We", "Us", or "Our" refers to Noburo Business Services LLP, the legal entity operating the Nebulaa platform under the laws of India.',
              '"Platform" refers to the Nebulaa application, website (nebulaa.ai), associated APIs, tools, dashboards, and any related services, including Founder OS and all named product modules (Gravity, Pulsar, Infinity, Singularity, Atom, etc.).',
              '"User", "You", or "Your" refers to any individual or entity that registers for, accesses, or uses the Platform.',
              '"Trial Period" means the free, time-limited access period granted before a paid subscription commences.',
              '"Subscription" means a paid plan that grants continued access to the Platform after the Trial Period.',
              '"Content" refers to all data, inputs, outputs, text, decisions, learnings, records, reports, and materials submitted to or generated through the Platform.',
              '"AI Output" refers to suggestions, recommendations, analyses, or insights generated by the Platform\'s artificial intelligence or machine learning components.',
              '"Services" refers to all features, functions, modules, and capabilities made available through the Platform.',
            ]} />
          </Section>

          <Section number={2} title="Acceptance of Terms">
            <P><strong className="text-ink">2.1</strong> By creating an account, clicking &quot;I Agree&quot;, or using any part of the Platform, you confirm that: you are at least 18 years of age; you have the legal authority to enter into a binding agreement on behalf of yourself or the entity you represent; you are not prohibited by applicable law from entering into such an agreement; and you have read, understood, and agree to these Terms in their entirety.</P>
            <P><strong className="text-ink">2.2</strong> If you are accepting these Terms on behalf of a company, organisation, or other legal entity, you warrant that you have the authority to bind such entity to these Terms.</P>
            <P><strong className="text-ink">2.3</strong> We reserve the right to update or modify these Terms at any time. Material changes will be communicated via email or in-platform notification. Continued use of the Platform after such notification constitutes acceptance of the revised Terms.</P>
          </Section>

          <Section number={3} title="Account Registration & Security">
            <Numbered items={[
              'You must provide accurate, complete, and current information during registration and keep this information updated at all times.',
              'You are solely responsible for maintaining the confidentiality of your login credentials. You must notify us immediately at support@nebulaa.ai upon becoming aware of any unauthorised use of your account.',
              'We are not liable for any loss or damage arising from your failure to safeguard your account credentials.',
              'One account per individual or entity is permitted unless expressly authorised by us in writing. You may not share account access with third parties.',
              'We reserve the right to suspend or terminate accounts that we reasonably believe are being used in violation of these Terms, applicable laws, or our community standards.',
            ]} />
          </Section>

          <Section number={4} title="Free Trial">
            <P><strong className="text-ink">4.1</strong> We may offer a free Trial Period at our sole discretion. The Trial Period allows limited or full access to the Platform for evaluation purposes only.</P>
            <P><strong className="text-ink">4.2</strong> By commencing a trial, you agree that: the trial is provided on an &quot;as-is&quot; basis with no warranties of any kind; we may modify, suspend, or terminate your trial access at any time without notice; and data and content created during the trial may be retained, deleted, or transitioned upon conversion to a paid plan, at our discretion.</P>
            <P><strong className="text-ink">4.3</strong> If you do not upgrade to a paid Subscription upon expiry of the Trial Period, your access will be restricted or terminated. We are not obligated to preserve data post-trial unless you have an active Subscription.</P>
          </Section>

          <Section number={5} title="Subscriptions, Billing & Payments">
            <P><strong className="text-ink">5.1</strong> Paid Subscriptions are offered on a periodic basis (monthly, quarterly, annual, or as otherwise stated during checkout). Subscription fees are displayed at the time of purchase and are subject to change with advance notice.</P>
            <P><strong className="text-ink">5.2</strong> All payments are processed through Razorpay. By providing payment details, you authorise us to charge the applicable fees on the billing cycle commensurate with your chosen plan.</P>
            <P><strong className="text-ink">5.3</strong> Unless you cancel your Subscription before the renewal date, your Subscription will automatically renew for the same period at the then-current rate.</P>
            <P><strong className="text-ink">5.4</strong> All fees are quoted in Indian Rupees (INR) unless otherwise stated. Applicable taxes, including Goods and Services Tax (GST), will be added at the prevailing rate.</P>
            <P><strong className="text-ink">5.5</strong> Failure to pay or charge-backs may result in immediate suspension of access. We reserve the right to charge interest on overdue amounts at a rate of 1.5% per month or the maximum rate permitted by law, whichever is lower.</P>
            <P><strong className="text-ink">5.6</strong> We reserve the right to modify our pricing at any time. Any changes to your Subscription pricing will be communicated with at least 30 days&apos; advance notice prior to the next billing cycle.</P>
          </Section>

          <Section number={6} title="Refund Policy">
            <P><strong className="text-ink">6.1</strong> Given the nature of digital services, all payments made are non-refundable except as expressly stated below or required by applicable law.</P>
            <P><strong className="text-ink">6.2</strong> A refund may be considered in the following limited circumstances:</P>
            <Ul items={[
              'You were charged incorrectly due to a billing error on our part',
              'The Platform experienced material service downtime (greater than 72 consecutive hours) within the first 7 days of a new paid Subscription, directly attributable to our failure, and you notify us within that period',
            ]} />
            <P><strong className="text-ink">6.3</strong> All refund requests must be submitted to <a href="mailto:support@nebulaa.ai" className="text-gold-text hover:underline">support@nebulaa.ai</a> within 7 days of the charge in question. We will process approved refunds within 10 business days.</P>
            <P><strong className="text-ink">6.4</strong> We do not offer refunds for partial periods, unused features, or dissatisfaction with AI Outputs or results.</P>
          </Section>

          <Section number={7} title="Platform Use & Acceptable Use Policy">
            <SubHeading>7.1 Permitted Use</SubHeading>
            <P>You may use the Platform solely for your own internal business purposes as a founder, operator, or professional, subject to your Subscription plan and these Terms.</P>
            <SubHeading>7.2 Prohibited Conduct</SubHeading>
            <P>You must not:</P>
            <Ul items={[
              'Use the Platform for any unlawful purpose or in violation of any applicable local, national, or international law or regulation',
              'Attempt to gain unauthorised access to any part of the Platform, other accounts, or associated systems or networks',
              'Reverse engineer, decompile, disassemble, or attempt to extract the source code, algorithms, or underlying models of the Platform',
              'Scrape, harvest, or systematically download data from the Platform without prior written authorisation',
              'Sell, resell, sublicence, rent, or commercially exploit the Platform or your access to it, except as expressly permitted',
              'Upload or transmit any material that contains viruses, malware, or any other harmful code',
              'Interfere with or disrupt the integrity, performance, or availability of the Platform or its infrastructure',
              'Use the Platform to send unsolicited communications, spam, or phishing content',
              'Impersonate any person or entity or misrepresent your affiliation with any person or entity',
              'Use AI Outputs to create competing products or services without our prior written consent',
              'Use the Platform in any manner that could bring the Company, the Nebulaa brand, or our partners into disrepute',
            ]} />
            <SubHeading>7.3 Content Standards</SubHeading>
            <P>All content you submit to the Platform must be lawful, accurate, and not infringe any third-party intellectual property, privacy, or other rights. You are solely responsible for all content you submit.</P>
          </Section>

          <Section number={8} title="Intellectual Property">
            <P><strong className="text-ink">8.1</strong> All rights, title, and interest in and to the Platform — including but not limited to its software, code, architecture, design, branding, AI models, workflows, templates, documentation, and all updates and derivatives thereof — are and shall remain the exclusive property of Noburo Business Services LLP or our licensors.</P>
            <P><strong className="text-ink">8.2</strong> These Terms do not grant you any ownership rights in the Platform. You receive only a limited, non-exclusive, non-transferable, revocable licence to use the Platform during the term of your Subscription in accordance with these Terms.</P>
            <P><strong className="text-ink">8.3</strong> You retain ownership of the original input data and business information you provide to the Platform. By submitting content, you grant us a non-exclusive, royalty-free, worldwide licence to use, process, and analyse your content solely for the purpose of providing and improving the Services.</P>
            <P><strong className="text-ink">8.4</strong> Any feedback, suggestions, or ideas you provide regarding the Platform may be used by us without restriction, compensation, or attribution.</P>
            <P><strong className="text-ink">8.5</strong> &quot;Nebulaa&quot;, &quot;Founder OS&quot;, &quot;Gravity&quot;, &quot;Pulsar&quot;, &quot;Infinity&quot;, &quot;Singularity&quot;, &quot;Atom&quot;, and all associated logos and marks are proprietary to Noburo Business Services LLP. You may not use our trademarks or branding without prior written permission.</P>
          </Section>

          <Section number={9} title="AI-Generated Outputs — Disclaimer & Limitations">
            <P><strong className="text-ink">9.1</strong> The Platform utilises artificial intelligence and machine learning technologies to generate insights, recommendations, action plans, and analyses (collectively, &quot;AI Outputs&quot;).</P>
            <P><strong className="text-ink">9.2</strong> AI Outputs are provided for informational and productivity purposes only. They are not a substitute for professional business, financial, legal, or strategic advice.</P>
            <P><strong className="text-ink">9.3</strong> We make no warranty that AI Outputs will be accurate, complete, current, suitable for any particular purpose, or free from errors. You acknowledge that AI systems can produce incorrect, outdated, or contextually inappropriate results.</P>
            <P><strong className="text-ink">9.4</strong> All business decisions, actions, and strategies taken based on AI Outputs remain your sole responsibility. We expressly disclaim all liability for any outcomes arising from your reliance on AI Outputs.</P>
            <P><strong className="text-ink">9.5</strong> You must independently verify any AI Output before acting upon it, particularly for significant business decisions.</P>
          </Section>

          <Section number={10} title="Data & Privacy">
            <P>Your use of the Platform is also governed by our <a href="/privacy-policy" className="text-gold-text hover:underline">Privacy Policy</a>, which is incorporated into these Terms by reference. By using the Platform, you consent to the collection, storage, processing, and use of your data as described in the Privacy Policy.</P>
          </Section>

          <Section number={11} title="Third-Party Integrations & Services">
            <P>The Platform may integrate with or contain links to third-party tools, APIs, and services (e.g., payment gateways, CRM tools, email platforms). These third-party services are governed by their own terms and privacy policies. We do not endorse, control, or assume responsibility for third-party services. Your use of such services is at your own risk.</P>
          </Section>

          <Section number={12} title="Service Availability & Modifications">
            <P><strong className="text-ink">12.1</strong> We strive to maintain Platform availability but do not guarantee uninterrupted, error-free, or continuous access. The Platform may be temporarily unavailable due to scheduled maintenance, technical failures, or circumstances beyond our control.</P>
            <P><strong className="text-ink">12.2</strong> We reserve the right to modify, update, enhance, deprecate, or discontinue any feature or module of the Platform at any time, with reasonable notice where practicable.</P>
            <P><strong className="text-ink">12.3</strong> In the event of a complete discontinuation of the Platform, we will provide at least 30 days&apos; advance notice and, at our discretion, offer a pro-rated refund for unused prepaid Subscription periods.</P>
          </Section>

          <Section number={13} title="Disclaimers of Warranty">
            <div className="bg-gold/5 border border-gold/15 rounded-xl p-4 font-body text-sm text-ink-2 leading-relaxed">
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE PLATFORM AND ALL SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. WE EXPRESSLY DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, TITLE, NON-INFRINGEMENT, AND UNINTERRUPTED OR ERROR-FREE OPERATION.
            </div>
          </Section>

          <Section number={14} title="Limitation of Liability">
            <div className="bg-gold/5 border border-gold/15 rounded-xl p-4 font-body text-sm text-ink-2 leading-relaxed mb-3">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL NOBURO BUSINESS SERVICES LLP, ITS DIRECTORS, OFFICERS, EMPLOYEES, PARTNERS, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES; LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITIES; LOSSES ARISING FROM RELIANCE ON AI OUTPUTS; OR ANY MATTER BEYOND OUR REASONABLE CONTROL.
            </div>
            <P><strong className="text-ink">14.2</strong> Our aggregate liability to you shall not exceed the total fees paid by you to us in the three (3) months immediately preceding the event giving rise to the claim.</P>
            <P><strong className="text-ink">14.3</strong> Nothing in these Terms limits or excludes liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded by law.</P>
          </Section>

          <Section number={15} title="Indemnification">
            <P>You agree to indemnify, defend, and hold harmless Noburo Business Services LLP and its officers, directors, employees, partners, and agents from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or related to: your use of or access to the Platform; your violation of these Terms; your violation of any applicable law or third-party rights; any content or data you submit to the Platform; or any business decisions made using AI Outputs.</P>
          </Section>

          <Section number={16} title="Confidentiality">
            <P><strong className="text-ink">16.1</strong> Each party agrees to keep confidential all non-public information of the other party that is disclosed in connection with these Terms or the use of the Platform, using at least the same standard of care as it uses to protect its own confidential information, but no less than reasonable care.</P>
            <P><strong className="text-ink">16.2</strong> This obligation does not apply to information that is or becomes publicly available without breach; was independently developed without reference to confidential information; or is required to be disclosed by law or a court order.</P>
            <P><strong className="text-ink">16.3</strong> This confidentiality obligation survives termination or expiry of these Terms for a period of two (2) years.</P>
          </Section>

          <Section number={17} title="Term & Termination">
            <P><strong className="text-ink">17.1</strong> These Terms commence on the date you first access the Platform and continue until your Subscription is terminated or expires.</P>
            <P><strong className="text-ink">17.2</strong> You may terminate your Subscription at any time through your account settings or by contacting <a href="mailto:support@nebulaa.ai" className="text-gold-text hover:underline">support@nebulaa.ai</a>. Termination is effective at the end of the current billing cycle.</P>
            <P><strong className="text-ink">17.3</strong> We may suspend or terminate your access immediately, without notice, if you materially breach these Terms and fail to remedy the breach within 7 days of notice; we are required to do so by law; you engage in fraudulent, abusive, or illegal conduct; or continued provision of access poses a security risk to the Platform or other users.</P>
            <P><strong className="text-ink">17.4</strong> Upon termination, your licence to use the Platform immediately ceases. Provisions that by their nature should survive termination (including Sections 8, 9, 13, 14, 15, 16, 19, 20) shall continue in full force.</P>
          </Section>

          <Section number={18} title="Governing Law & Dispute Resolution">
            <P><strong className="text-ink">18.1</strong> These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles.</P>
            <P><strong className="text-ink">18.2</strong> Any dispute shall be resolved through the following process:</P>
            <Ul items={[
              'Step 1 — Informal Resolution: The aggrieved party shall notify the other in writing, and both parties shall make good-faith efforts to resolve the dispute within 30 days.',
              'Step 2 — Mediation: If unresolved, the parties shall submit to mediation under the auspices of a mutually agreed mediator in Chennai, Tamil Nadu.',
              'Step 3 — Arbitration: If mediation fails, the dispute shall be resolved by binding arbitration under the Arbitration and Conciliation Act, 1996, with proceedings conducted in Chennai, Tamil Nadu, in the English language.',
            ]} />
            <P><strong className="text-ink">18.3</strong> Subject to the arbitration clause above, you consent to the exclusive jurisdiction of the courts located in Chennai, Tamil Nadu, India.</P>
            <P><strong className="text-ink">18.4</strong> You waive any right to participate in a class action lawsuit or class-wide arbitration.</P>
          </Section>

          <Section number={19} title="Force Majeure">
            <P>We shall not be liable for any delay or failure in performance resulting from events beyond our reasonable control, including but not limited to acts of God, natural disasters, pandemics, government actions, wars, civil disturbances, internet outages, power failures, or failures of third-party services.</P>
          </Section>

          <Section number={20} title="General Provisions">
            <SubHeading>20.1 Entire Agreement</SubHeading>
            <P>These Terms, together with the Privacy Policy and any other agreements or policies incorporated by reference, constitute the entire agreement between you and us regarding the Platform and supersede all prior agreements and understandings.</P>
            <SubHeading>20.2 Severability</SubHeading>
            <P>If any provision of these Terms is found to be invalid, illegal, or unenforceable, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.</P>
            <SubHeading>20.3 Waiver</SubHeading>
            <P>Our failure to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision.</P>
            <SubHeading>20.4 Assignment</SubHeading>
            <P>You may not assign or transfer any rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations to an affiliate, successor, or acquirer of the business.</P>
            <SubHeading>20.5 No Partnership</SubHeading>
            <P>Nothing in these Terms creates any partnership, joint venture, agency, franchise, or employment relationship between you and us.</P>
            <SubHeading>20.6 Notices</SubHeading>
            <P>Notices to us shall be sent to <a href="mailto:legal@nebulaa.ai" className="text-gold-text hover:underline">legal@nebulaa.ai</a> or by post to the registered address of Noburo Business Services LLP. Notices to you shall be sent to the email address associated with your account.</P>
            <SubHeading>20.7 Language</SubHeading>
            <P>These Terms are written in English. In the event of any inconsistency between an English version and a translated version, the English version shall prevail.</P>
          </Section>

          <Section number={21} title="Contact Information">
            <div className="bg-gold/5 border border-gold/15 rounded-xl p-4 space-y-1">
              <p className="font-semibold text-ink">Noburo Business Services LLP</p>
              <p className="text-ink-2">Operating Platform: Nebulaa (nebulaa.ai)</p>
              <p className="text-ink-2">Support Email: <a href="mailto:support@nebulaa.ai" className="text-gold-text hover:underline">support@nebulaa.ai</a></p>
              <p className="text-ink-2">Website: <a href="https://www.nebulaa.ai" className="text-gold-text hover:underline">https://www.nebulaa.ai</a></p>
            </div>
            <P>By using Nebulaa, you acknowledge that you have read, understood, and agreed to these Terms & Conditions.</P>
          </Section>
        </div>

        {/* Footer note */}
        <div className="mt-12 pt-8 border-t border-rule flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <p className="font-body text-xs text-faint">Last Updated: 10 March 2025 · Document Version: 1.0</p>
          <p className="font-body text-xs text-faint">© 2025 Noburo Business Services LLP. All rights reserved.</p>
        </div>
      </div>
    </main>
  )
}
