export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  category: string
  readTime: string
  date: string
  author: string
  headerColor: string
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'gtm-experiment-linkedin-daily-posting-30-days',
    title: 'GTM Experiment #1: We Posted on LinkedIn Every Day for 30 Days. Here\'s the Data.',
    excerpt: 'A Bangalore SaaS founder ran a 30-day LinkedIn experiment using Gravity. Here\'s exactly what happened — the good, the bad, and the unexpected DMs.',
    category: 'GTM Experiments',
    readTime: '6 min read',
    date: 'March 15, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-blue-500/20 to-blue-400/5',
  },
  {
    slug: 'gtm-experiment-cold-calling-100-leads',
    title: 'GTM Experiment #2: We Had Pulsar Call 100 Leads in One Week. 14 Booked Demos.',
    excerpt: 'A D2C founder gave Pulsar 100 cold leads from a trade show. One week later: 14 demo calls booked, 3 paying customers. Here\'s the full breakdown.',
    category: 'GTM Experiments',
    readTime: '7 min read',
    date: 'March 12, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-orange-500/20 to-orange-400/5',
  },
  {
    slug: 'saas-founder-40-leads-on-a-flight',
    title: 'How a SaaS Founder in Bangalore Got 40 Warm Leads While on a Flight',
    excerpt: 'We walked through exactly how Pulsar was set up, what script it used, and how 40 leads were pre-qualified without a single call made by the founder.',
    category: 'GTM Strategy',
    readTime: '5 min read',
    date: 'March 10, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-brand-gold/20 to-brand-gold/5',
  },
  {
    slug: 'gtm-experiment-whatsapp-vs-email-outreach',
    title: 'GTM Experiment #3: WhatsApp vs Email Outreach — We Tested Both for 2 Weeks',
    excerpt: 'Same leads, same message, different channel. WhatsApp got 4x the reply rate. Here\'s everything we learned.',
    category: 'GTM Experiments',
    readTime: '5 min read',
    date: 'March 8, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-green-500/20 to-green-400/5',
  },
  {
    slug: 'linkedin-strategy-gravity-runs-for-you',
    title: 'The 7-Step LinkedIn Strategy That Gravity Runs For You (That Would Take You 8 Hours/Week)',
    excerpt: 'We mapped out the exact content system Gravity uses — from brand voice ingestion to post scheduling — and why it outperforms manual posting every time.',
    category: 'Marketing Automation',
    readTime: '7 min read',
    date: 'March 5, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-brand-warm-gray to-brand-off-white',
  },
  {
    slug: 'gtm-experiment-competitor-content-strategy',
    title: 'GTM Experiment #4: We Copied Our Competitor\'s Content Strategy for 3 Weeks',
    excerpt: 'What happens when you systematically replicate a competitor\'s LinkedIn strategy? Surprising results — and one big lesson about brand voice.',
    category: 'GTM Experiments',
    readTime: '6 min read',
    date: 'March 3, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-purple-500/20 to-purple-400/5',
  },
  {
    slug: 'stop-writing-your-own-captions',
    title: 'Stop Writing Your Own Captions. Here\'s What to Do Instead.',
    excerpt: 'A direct guide for early-stage founders who are spending more time on content than on customers — and how to fix that in under an hour.',
    category: 'Founder Playbook',
    readTime: '4 min read',
    date: 'February 28, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-brand-off-white to-white',
  },
  {
    slug: 'gtm-experiment-founder-story-content',
    title: 'GTM Experiment #5: Founder Story Posts vs Product Posts — Which Got More Leads?',
    excerpt: 'We split-tested 20 founder story posts against 20 product-feature posts over 6 weeks. The results changed how we think about content forever.',
    category: 'GTM Experiments',
    readTime: '5 min read',
    date: 'February 25, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-brand-gold/25 to-brand-gold/5',
  },
  {
    slug: 'founder-mistake-hiring-sales-before-product-market-fit',
    title: 'The Mistake 80% of Founders Make: Hiring Sales Before Product-Market Fit',
    excerpt: 'Hiring a sales team before you\'ve found PMF is the fastest way to burn runway and morale. Here\'s what to do instead.',
    category: 'Founder Mistakes',
    readTime: '6 min read',
    date: 'February 20, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-red-500/20 to-red-400/5',
  },
  {
    slug: 'founder-mistake-inconsistent-social-media',
    title: 'Why Inconsistent Social Media Is Costing You More Than You Think',
    excerpt: 'Posting 3 times one week, nothing for a month — the algorithm punishes this. So do your potential customers. Here\'s the real cost.',
    category: 'Founder Mistakes',
    readTime: '5 min read',
    date: 'February 15, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-pink-500/20 to-pink-400/5',
  },
  {
    slug: 'founder-mistake-chasing-every-lead',
    title: 'Stop Chasing Every Lead. Here\'s How to Qualify Fast and Close More.',
    excerpt: 'Most early-stage founders spend 40% of their time on leads that will never convert. Here\'s a system to know in 5 minutes if a lead is worth pursuing.',
    category: 'Founder Mistakes',
    readTime: '6 min read',
    date: 'February 10, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-cyan-500/20 to-cyan-400/5',
  },
  {
    slug: 'nebulaa-vs-buffer-scheduling-tools',
    title: 'Nebulaa vs Buffer: Why a Scheduling Tool Isn\'t Enough for Growth',
    excerpt: 'Buffer schedules posts. Nebulaa creates them, schedules them, and qualifies the leads they generate. Here\'s a full comparison.',
    category: 'Comparisons',
    readTime: '7 min read',
    date: 'February 5, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-blue-600/20 to-blue-500/5',
  },
  {
    slug: 'nebulaa-vs-jasper-ai-content',
    title: 'Nebulaa vs Jasper AI: One Writes for You, One Publishes and Follows Up',
    excerpt: 'Jasper is a great content writer. But it doesn\'t post, track rivals, or call your leads. Here\'s how they compare for founder-led GTM.',
    category: 'Comparisons',
    readTime: '6 min read',
    date: 'January 30, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-violet-500/20 to-violet-400/5',
  },
  {
    slug: 'nebulaa-vs-clay-lead-enrichment',
    title: 'Nebulaa vs Clay: Two Approaches to AI-Powered Lead Generation',
    excerpt: 'Clay enriches and sequences leads. Nebulaa messages them on WhatsApp, qualifies them, and handles the entire conversation. Here\'s when to use each.',
    category: 'Comparisons',
    readTime: '7 min read',
    date: 'January 25, 2026',
    author: 'Nebulaa Team',
    headerColor: 'from-emerald-500/20 to-emerald-400/5',
  },
]
