/**
 * Scans public/media and writes the list of filled asset slots.
 *
 * Client components can't touch the filesystem, so presence is resolved once
 * at build time into a plain module both server and client code can import.
 * Runs automatically via `prebuild`; run `npm run media:scan` after dropping
 * files in during local development.
 */
import { readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const mediaDir = join(root, 'public', 'media')
const outFile = join(root, 'lib', 'mediaManifest.generated.ts')

if (!existsSync(mediaDir)) mkdirSync(mediaDir, { recursive: true })

const files = readdirSync(mediaDir)
  .filter(f => !f.startsWith('.') && f !== 'README.md')
  .sort()

writeFileSync(
  outFile,
  `// GENERATED by scripts/scan-media.mjs — do not edit.\n` +
    `// Files currently present in public/media/.\n` +
    `export const presentMedia: readonly string[] = ${JSON.stringify(files, null, 2)}\n`,
  'utf8',
)

console.log(`media:scan — ${files.length} file(s) in public/media`)
